# Generated by Django 3.2.8 on 2021-10-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('AD', 'Admin'), ('CU', 'Customer')], default='CU', max_length=50),
        ),
    ]
