# Generated by Django 3.2.8 on 2021-10-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0003_auto_20211021_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_blocked',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_subscribed',
        ),
        migrations.AddField(
            model_name='user',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
