# Generated by Django 3.2.8 on 2021-10-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0004_auto_20211021_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_validity',
            field=models.IntegerField(default=0),
        ),
    ]
