# Generated by Django 3.2.8 on 2021-10-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0005_alter_subscription_subscription_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_validity',
            field=models.IntegerField(default=0, verbose_name='subscription_validity (Months)'),
        ),
    ]
