# Generated by Django 3.2.8 on 2021-10-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0007_rename_subscriptioncategory_subscriptiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
