# Generated by Django 3.2.8 on 2021-10-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0008_alter_subscriptiontype_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiontype',
            old_name='category_name',
            new_name='type_name',
        ),
    ]
