# Generated by Django 3.2.8 on 2021-10-21 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0009_rename_category_name_subscriptiontype_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_name', models.CharField(blank=True, max_length=255, null=True)),
                ('content_description', models.TextField(blank=True, max_length=2000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='subscriptiontype',
            name='allowed_videos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_type', to='video_stream_app.videocontent'),
        ),
    ]
