# Generated by Django 3.2.8 on 2021-10-21 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0010_auto_20211021_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontype',
            name='allowed_videos',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='allowed_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_type', to='video_stream_app.subscriptiontype'),
        ),
    ]
