# Generated by Django 3.2.8 on 2021-10-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0011_auto_20211021_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='content_file'),
        ),
    ]
