# Generated by Django 3.2.8 on 2021-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0013_auto_20211022_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocontent',
            name='allowed_subscription',
            field=models.ManyToManyField(related_name='subscription_type', to='video_stream_app.SubscriptionType'),
        ),
    ]
