# Generated by Django 3.2.8 on 2021-10-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_stream_app', '0014_alter_videocontent_allowed_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='content_cover'),
        ),
    ]
